// Tiny typed pub/sub bridging per-page components (SolveView, QuizRunner…) to
// the globally-mounted companion widget. A module singleton is safe here: every
// emitter and the sole consumer are client components in the same browser
// bundle. A short replay buffer covers events fired before the widget finishes
// mounting (and makes dev-time HMR re-instantiation benign). No React imports —
// the widget subscribes inside useEffect.

export type CompanionEvent =
  | { type: "problemOpen"; title: string; difficulty?: string }
  | { type: "solved"; problemId: string; title: string; elapsedMs: number | null; attempts: number }
  | {
      type: "verdict";
      verdict: "suboptimal" | "incorrect" | "incomplete";
      title: string;
      attempts: number;
    }
  | { type: "hint"; title: string; level: number }
  | { type: "quiz"; topic: string; scorePct: number }
  // A coach nudge already generated by the coach LLM call (possibly already in
  // the character's voice) — display-only, no further LLM work.
  | { type: "coachLine"; text: string }
  | { type: "settingsChanged" };

type Listener = (e: CompanionEvent) => void;

const REPLAY_MAX = 10;
const REPLAY_WINDOW_MS = 5000;

const listeners = new Set<Listener>();
const replay: { at: number; e: CompanionEvent }[] = [];
let lastActivityAt = 0;

export function emitCompanionEvent(e: CompanionEvent): void {
  replay.push({ at: Date.now(), e });
  if (replay.length > REPLAY_MAX) replay.shift();
  for (const fn of [...listeners]) {
    try {
      fn(e);
    } catch {
      // one bad listener never breaks the rest
    }
  }
}

/** Subscribe; recent events (younger than the replay window) are replayed immediately. */
export function subscribeCompanion(fn: Listener): () => void {
  listeners.add(fn);
  const cutoff = Date.now() - REPLAY_WINDOW_MS;
  for (const { at, e } of replay) {
    if (at >= cutoff) fn(e);
  }
  return () => {
    listeners.delete(fn);
  };
}

/** Call on every editor/input keystroke so the companion stays quiet while the user types. */
export function noteActivity(): void {
  lastActivityAt = Date.now();
}

export function getLastActivityAt(): number {
  return lastActivityAt;
}

export function emitCompanionSettingsChanged(): void {
  emitCompanionEvent({ type: "settingsChanged" });
}
